# Generated by Django 3.2.12 on 2023-02-11 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FormLinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response', jsonfield.fields.JSONField()),
                ('is_send', models.BooleanField(default=False)),
                ('on_validation', models.BooleanField(default=False)),
                ('form_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FormLinks.formlinks')),
            ],
            options={
                'db_table': 'response_collector',
            },
        ),
    ]
