# Generated by Django 3.2.12 on 2022-12-28 23:35

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_stamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('response', jsonfield.fields.JSONField()),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'response_collector',
            },
        ),
    ]
