# Generated by Django 3.2.12 on 2022-12-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResponseCollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecollector',
            name='on_validation',
            field=models.BooleanField(default=False),
        ),
    ]
