from settings import *

DEBUG = True

TEMPLATES[0]['OPTIONS']['debug'] = True

SECRET_KEY = '<YOUR KEY>'

HOST_PORT = 4601

EMAIL_HOST_USER = ''
DEFAULT_FROM_EMAIL = ''
EMAIL_HOST_PASSWORD = '<PASSWORD OR SECURITY CODE OF APP>'
RECIPIENT = ''
