# Generated by Django 3.2.12 on 2023-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('wait_for_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'form_link',
            },
        ),
    ]
