# Generated by Django 3.2.12 on 2023-02-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormLinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlinks',
            name='link',
            field=models.CharField(max_length=128),
        ),
    ]
