# Generated by Django 3.2.12 on 2023-02-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormLinks', '0002_alter_formlinks_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlinks',
            name='order_number',
            field=models.BigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
