# Generated by Django 3.2.12 on 2023-03-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormLinks', '0003_formlinks_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlinks',
            name='order_number',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
